services:
  db:
    image: postgres:latest
    container_name: currency_converter_db_ctn
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
